### ISSUE TITLE
A donation account through PayPal

### ISSUE THREAD

**Issue by logangbrown** [markhaslam/familysummit.org#8]
I know you were working on this, Mark, so it might be taken care of. There is some information in the code that looks like it used to get to the right PayPal donation page, I just don't know if it's all taken care of, or what else needs to be done on it. Go ahead and close this if it's taken care of.

**Comment by markhaslam** [comment]
I believe what that button links to is just a temporary filler I made until she gets an account set up. She needs to register an account with PayPal as a non-profit and then we need to link her account to the button after she creates it. She may have forgotten that she needs to get an account set up since it was forever ago that I talked with her about it. We will need to remind her and and maybe explain where or how she sets up an account and register as a non-profit.

**Comment by logangbrown** [comment]
We're just going to comment out this code for now, her bank apparently has some special thing it does. We can add the link in if she gets a paypal account set up.
